backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "dimensions"
    label: "Dimensions"
    label_singular: 'Dimension'
    folder: "dimensions"
    create: true
    slug: "{{size}}{{unit}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "stylevar"}
      - {label: "Size", name: "size", widget: "number"}
      - {label: "Unit", name: "unit", widget: "select", options: ["em", "rem", "px", "%", "vh", "vw", "vmin", "vmax", "ex", "cm", "mm", "in", "pt", "pc", "ch"]}
      - {label: "Description", name: "description", widget: "markdown"}
